### ISSUE TITLE
A PConv followed by a PWConv well approximates the regular Conv 3 × 3,is it similar in speed

### ISSUE THREAD

**Issue by wsy-yjys** [JierunChen/FasterNet#1]
I read your paper. It was great!  And I have a question, the paper says “A PConv followed by a PWConv well approximates the regular Conv 3 × 3” , I'm very curious are they similar in speed, thank you~

**Comment by JierunChen** [comment]
Thanks for your interest in this work. A PConv followed by a PWConv well approximates and is $2\sim7\times$ faster than a regular Conv 3 × 3. The speedup varies for different feature map sizes and devices, as shown in the following table:

| Operator  <br> $\times10$ layers  | Feature map size | FLOPs (M) | Throughput <br> ($\times1000$ fps) <br> on GPU | Latency (ms) <br> on CPU | Latency (ms) <br> on ARM | 
| :----------------------: | :----------------------: | :----------------------: | :----------------------: | :----------------------: | :----------------------: |
| Conv $3\times3$  | $96\times56\times56$ <br> $192\times28\times28$ <br> $384\times14\times14$ <br> $768\times7\times7$| 2601  | 3.01 <br> 4.89 <br> 4.56 <br> 3.16 |  35.67 <br> 28.41 <br> 31.85  <br> 62.71 |  780  <br> 620  <br> 595 <br> 662 | 
| PConv 3$\times$3 with $r=\frac{1}{4}$ <br> followed by a PWConv | $96\times56\times56$ <br> $192\times28\times28$ <br> $384\times14\times14$ <br> $768\times7\times7$| 451   | 6.97 <br> 9.58 <br> 11.43 <br> 10.46 |  7.88 <br> 5.42 <br> 6.86 <br> 8.34 |  167<br>133<br>116<br>121 | 
| PConv 3$\times$3 with $r=\frac{1}{4}$ | $96\times56\times56$ <br> $192\times28\times28$ <br> $384\times14\times14$ <br> $768\times7\times7$| 162   | 15.39 <br> 20.51 <br> 37.21 <br> 43.24 |  4.74 <br> 2.38 <br> 3.32 <br> 3.95 |  81.70<br>62.69<br>48.19<br>47.52 | 
| PWConv (Conv $1\times1$) | $96\times56\times56$ <br> $192\times28\times28$ <br> $384\times14\times14$ <br> $768\times7\times7$| 289   | 12.75 <br> 17.98 <br> 16.49 <br> 13.79 |  3.14 <br> 3.04 <br> 3.54 <br> 4.39 |  85.07<br>70.50<br>67.38<br>73.58 |

**Comment by wsy-yjys** [comment]
You are very careful. Thank you very much
