### ISSUE TITLE
some differences

### ISSUE THREAD

**Issue by luckydog11** [JierunChen/FasterNet#11]
In your paper,  patch_embed module has acti, but your code has no acti, so is patch_mering module, what's going on here? Looking forward to your reply.

**Comment by JierunChen** [comment]
Hi, thanks for pointing this out. There are no activations after PatchEmbed and PatchMerging. We'll update the appendix accordingly.

**Comment by luckydog11** [comment]
> Hi, thanks for pointing this out. There are no activations after PatchEmbed and PatchMerging. We'll update the appendix accordingly.

thank you for your reply, but I want to know there is any impact of this.

**Comment by JierunChen** [comment]
> > Hi, thanks for pointing this out. There are no activations after PatchEmbed and PatchMerging. We'll update the appendix accordingly.
> 
> thank you for your reply, but I want to know there is any impact of this.

Hi, we haven't conducted an ablation study on this. Feel free to try it. If the models turn out to be the same in accuracy, it's preferred to remove those activations as they introduce additional latency.

**Comment by luckydog11** [comment]
ok , thank you
