### ISSUE TITLE
About Evaluation

### ISSUE THREAD

**Issue by wsy-yjys** [JierunChen/FasterNet#12]
> To measure the latency on CPU/ARM and throughput on GPU (if any), run
> ```
> python train_test.py -c cfg/fasternet_t0.yaml \
> --checkpoint_path model_ckpt/fasternet_t0-epoch=281-val_acc1=71.9180.pth \
> --data_dir ../../data/imagenet --test_phase -g 1 -e 32  --measure_latency --fuse_conv_bn
> ```

1. question1: in the command，`--test_phase` means what? 
2. question2: If use `--measure_latency` and  `--test_phase` at the same time, does `--test_phase` not work? thank you~

**Comment by JierunChen** [comment]
Hi, `--test_phase` enables the testing/validation on the imagenet val set. When `--measure_latency` is turned on,  `--test_phase` would be omitted. You may refer to [train_test.py](https://github.com/JierunChen/FasterNet/blob/master/train_test.py) for more details.

**Comment by wsy-yjys** [comment]
OK, Thank you！
