### ISSUE TITLE
How to measure the FLOPS the the model ?

### ISSUE THREAD

**Issue by jimmylin0979** [JierunChen/FasterNet#15]
> To better understand the situation, we compare the FLOPS of typical neural networks on an Intel CPU

As mentioned above, the paper compare the relationship of FLOPS and FLOPs  on some classic model, I'm interesting on the FLOPS of the model, can you briefly descirbe how do you measure the FLOPS of specific model ?  Thank you

**Comment by JierunChen** [comment]
Hi, to get FLOPS, we simply divide FLOPs by the latency. The ways how to get FLOPs and latency are both provided in the code. Please refer to [train_test.py](https://github.com/JierunChen/FasterNet/blob/master/train_test.py) and [utils.py](https://github.com/JierunChen/FasterNet/blob/master/utils/utils.py).

**Comment by jimmylin0979** [comment]
Got it, thanks !
