### ISSUE TITLE
general question: any plan to release the models? 

### ISSUE THREAD

**Issue by Mercurise** [JierunChen/FasterNet#2]
Hi, the work seems interesting to me. Do you have any plans to release the pre-trained models? Regarding the experiments with the Arm CPU, which software/compute library (Arm NN?) are you guys using? 

Can you share the strategy for the edge-device setting ups? I want to learn more about reproducing the results.  

Thanks,

**Comment by JierunChen** [comment]
Hi, the code, pre-trained models, and guidelines are under preparation and will all be released in several days. 

As for latency measurement on ARM (Raspberry Pi 4 Model B - 1GB with Raspberry Pi OS), we directly used PyTorch installed within a miniconda environment. You may also try some libraries (e.g., Arm NN) for model conversion and deployment.
