### ISSUE TITLE
Is it okay to increase the hierarchical stages?

### ISSUE THREAD

**Issue by bboogi** [JierunChen/FasterNet#20]
I found your paper and it was exciting. So, I want to apply FasterNet Block in my model.

But in  my model all the stages of extracting the feature map, the input channel is 6 and the output channel has 768. 

SO, Is it okay to increase the hierarchical stages 7 instead of 4 by applying embedding and merging layers?

**Comment by JierunChen** [comment]
Hi, thanks for your interest in this work. Feel free to add more stages to make it suitable for your task. But make sure the changes fit into your input resolution and the computation is allocated properly.

**Comment by bboogi** [comment]
Thank you! :)
