### ISSUE TITLE
Hello author, I have some questions about the ablation experiment section of your paper.

### ISSUE THREAD

**Issue by csjhhuc** [JierunChen/FasterNet#27]
In the ablation experiment，why is the throughput of w/r=1/8 in the T0 model smaller than w/r=1/4 and w/r=1/2?If you have time, please help me answer this question.

**Comment by JierunChen** [comment]
@csjhhuc Hi, to facilitate comparisons, the network widths are varied for the three variants. For T0$^∗$ w/ r = 1/8, we increase its network width to 42, and thus it throughput can possibly be smaller than the T0  w/ r = 1/4 with a network width of 40.

**Comment by csjhhuc** [comment]
Thank you very much for your answer to the previous question. May I ask what you mean is? When w/r=1/8 in T0, due to the low number of channels for convolution in the network, you are concerned that the network cannot obtain enough information. Therefore, by increasing the size of the feature map, network can obtain more spatial information for feature extraction.

**Comment by csjhhuc** [comment]
Also in the ablation experiment, I have some questions about your use of BN layers. Using the BN layer enables the network to have higher throughput and lower latency, but I want to gain a deeper understanding from a mathematical perspective of why using the BN layer has better performance than the LN layer. At the same time, you mentioned the fusion of BN layers and other convolutional layers, which means you used reparameterization methods in your code?
Looking forward to your reply.Wishing you a pleasant life.

**Comment by JierunChen** [comment]
> Thank you very much for your answer to the previous question. May I ask what you mean is? When w/r=1/8 in T0, due to the low number of channels for convolution in the network, you are concerned that the network cannot obtain enough information. Therefore, by increasing the size of the feature map, network can obtain more spatial information for feature extraction.

Hi, the main reason is to make the trade-off comparison more clear and easier. If we set the network width the same for r=1/8 and r=1/4, the one with r=1/8 will run a bit faster but have lower accuracy. Then we can not tell for sure that r=1/4 is better. But if we increase the network width when r=1/8, now it runs slower and has lower accuracy compared to the one with r=1/4. Now, we can say that r=1/4 is obviously better than r=1/8.

**Comment by JierunChen** [comment]
> Also in the ablation experiment, I have some questions about your use of BN layers. Using the BN layer enables the network to have higher throughput and lower latency, but I want to gain a deeper understanding from a mathematical perspective of why using the BN layer has better performance than the LN layer. At the same time, you mentioned the fusion of BN layers and other convolutional layers, which means you used reparameterization methods in your code? Looking forward to your reply.Wishing you a pleasant life.

In the ablation study, the BN attains similar accuracy to LN but runs faster than LN. As for their difference in terms of mathematical expression, you may refer to the following blogs:
[https://towardsdatascience.com/different-normalization-layers-in-deep-learning-1a7214ff71d6](https://towardsdatascience.com/different-normalization-layers-in-deep-learning-1a7214ff71d6)
[https://zhuanlan.zhihu.com/p/33173246](https://zhuanlan.zhihu.com/p/33173246)
 

As for merging a BN layer into a Conv layer (with a bias term), feel free to interpret it as a reparameterization trick.

**Comment by csjhhuc** [comment]
Thank you for your answer. Your answer has been of great help to my research and learning. Wishing you success in your studies and work.
