### ISSUE TITLE
Compared with mobileNetv3?

### ISSUE THREAD

**Issue by hanyueqian2** [JierunChen/FasterNet#3]
Your research is to be expected. After reading your paper, I'd like to ask if you've compared it with MobileNetV3. I want to replace my MobileNet V3 to speed up the model.

**Comment by JierunChen** [comment]
Hi, we haven't tried that as MobileNetV3 primarily relies on NAS, being orthogonal to our design focus. It also uses hardswish activation which is shown to be slow on some platforms (refer to [EfficientFormer](https://arxiv.org/abs/2206.01191)). Nevertheless, you are welcome to compare FasterNet with MobileNetV3 on your devices :)

**Comment by hanyueqian2** [comment]
Thank you for your answer.
