### ISSUE TITLE
Readme file improvement

### ISSUE THREAD

**Issue by yangshaobo0634** [JierunChen/FasterNet#37]
Clone this repo and install required packages:

git clone https://github.com/JierunChen/FasterNet
pip install -r requirements.txt

Here I recommend to do a small modification to run easily:

git clone https://github.com/JierunChen/FasterNet
cd fasternet
pip install -r requirements.txt

**Comment by JierunChen** [comment]
Hi, thanks for the notice. Revision has been made.
