### ISSUE TITLE
about fps

### ISSUE THREAD

**Issue by wsy-yjys** [JierunChen/FasterNet#7]
This problem has nothing to do with the project. It would be very grateful if you could reply me. 

![64baca6e4adb842feaab22334c40af5](https://user-images.githubusercontent.com/78601159/225489907-4b7a26bd-3263-48a3-b92c-f5b325674310.png)
The question is: Each row in the figure above is the same model reasoning 100 times average FPS, time and standard deviation of time on the same picture, but there are still fluctuations. Generally, which value should be taken for the paper？thank you~

**Comment by JierunChen** [comment]
You may choose the mean/median/highest fps as long as the standard is consistent for all models compared. In our paper, we report the highest fps for all models.

**Comment by wsy-yjys** [comment]
I got it. Thank you~

**Comment by wsy-yjys** [comment]
Another problem, when test the fps for all models, do all models need to fuse conv and bn? thank you~

**Comment by haiduo** [comment]
/
