### ISSUE TITLE
Have you used the Distillation?

### ISSUE THREAD

**Issue by Ezra-Yu** [JierunChen/FasterNet#8]
I notice there a teacher model in your config https://github.com/JierunChen/FasterNet/blob/9a30b0e0af2afb2364c18d74469b94f527cc2de3/cfg/fasternet_l.yaml#L30

**Comment by JierunChen** [comment]
Hi, we do not use distillation by default, as suggested in the config file:
`distillation_type: none   # do not use KD by default`. 
You may turn it on by using:
`distillation_type: hard  # should be better than soft`.

**Comment by Ezra-Yu** [comment]
Thanks
