### ISSUE TITLE
about fps

### ISSUE THREAD

**Issue by wsy-yjys** [JierunChen/FasterNet#9]
In your paper，when test the fps for all models, do all models fuse conv and bn? thank you~

**Comment by JierunChen** [comment]
Yes, we fuse conv and bn for all models if applicable, e.g., FasterNet, ShuffleNetV2, MobileNetV2, MobileViT, etc.

> In your paper，when test the fps for all models, do all models fuse conv and bn? thank you~

**Comment by wsy-yjys** [comment]
I know, Thanks a lot .
